url: 'http://127.0.0.1:4723/wd/hub'
desired_caps:
  platformName: 'Android'
  platformVersion: '7.1.2'
  deviceName: 'yeshen'
  appPackage: 'com.joinf.saasapp'
  appActivity: 'com.joinf.saasapp.SplashModule.SplashActivity'
#  automationName: 'uiautomator2'
  noReset: false
  newCommandTimeout: 120